#!/bin/bash

set -e

### BEGIN INIT INFO
# Provides:             mqtt-broker
# Required-Start:       $local_fs
# Required-Stop:        $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    MQTT Broker v2.0
### END INIT INFO


DAEMON_PATH="/mnt/data/mqtt-broker"
DAEMON="/mnt/data/vert.x-3.0.0/bin/vertx"
DAEMONOPTS="run io.github.giovibal.mqtt.MQTTBroker -cp $DAEMON_PATH/vertx-mqtt-broker-mod-2.0-SNAPSHOT-fat.jar -instances 2 -conf $DAEMON_PATH/config-2.0.json -cluster"

NAME="mqtt-broker-2.0"
DESC="$NAME daemon"
PIDFILE="/var/run/$NAME.pid"
SCRIPTNAME="/etc/init.d/$NAME"
LOGFILE="/var/log/$NAME.log"
JAVA_HOME="/opt/jdk"

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH
    PID=`$DAEMON $DAEMONOPTS >> $LOGFILE 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            #kill -HUP $PID
            #sleep 20
            while kill -HUP $PID 2>/dev/null; do sleep 1; done
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
